### ISSUE TITLE
Problem with identity.rkt

### ISSUE THREAD

**Issue by samth** [eu90h/racket-github-api#3]
When I try to install this package, I get a bunch of errors about a missing `identity.rkt` file.

**Comment by eu90h** [comment]
Terribly sorry. The file is used by the functional test suite. I was using my GitHub id to test and had it outside the repo so it wasn't committed by accident. I've added a dummy `identity.rkt` to the functional_tests directory. 

If you wish to run the tests, edit the credentials in that file. Anyways, that _should_ fix the problem.

**Comment by eu90h** [comment]
After some testing, the issue seems resolved. Thanks again for reporting, closing this out.
